"""first migrate

Revision ID: cf86656617b8
Revises: 
Create Date: 2022-04-27 16:04:12.326654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf86656617b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_BOOK',
    sa.Column('F_TYPE', sa.String(length=50), nullable=False),
    sa.Column('F_TITLE', sa.String(length=300), nullable=False),
    sa.Column('F_AUTHOR', sa.String(length=50), nullable=False),
    sa.Column('F_ISBN', sa.String(length=13), nullable=False),
    sa.Column('F_GENRE', sa.String(length=50), nullable=False),
    sa.Column('F_PRICE', sa.String(length=15), nullable=True),
    sa.Column('F_LANGUAGE', sa.String(length=50), nullable=False),
    sa.Column('F_SERIES', sa.String(length=200), nullable=True),
    sa.Column('F_SIZE', sa.String(length=50), nullable=False),
    sa.Column('F_SYNOPSIS', sa.String(length=5000), nullable=True),
    sa.Column('F_COVER', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('F_ISBN')
    )
    op.create_index(op.f('ix_T_BOOK_F_ISBN'), 'T_BOOK', ['F_ISBN'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_T_BOOK_F_ISBN'), table_name='T_BOOK')
    op.drop_table('T_BOOK')
    # ### end Alembic commands ###
